// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Data.proto</summary>
public static partial class DataReflection {

  #region Descriptor
  /// <summary>File descriptor for Data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpEYXRhLnByb3RvIjIKBFBvc2USFgoOZW5kRWZmZWN0b3JDb3IYASADKAIS",
          "EgoKam9pbnRBbmdsZRgCIAMoAiI4Cg5Kb2dKb2ludFBhcmFtcxIQCgh2ZWxv",
          "Y2l0eRgBIAMoAhIUCgxhY2NlbGVyYXRpb24YAiADKAIiPQoTSm9nQ29vcmRp",
          "bmF0ZVBhcmFtcxIQCgh2ZWxvY2l0eRgBIAMoAhIUCgxhY2NlbGVyYXRpb24Y",
          "AiADKAIiQwoPSk9HQ29tbW9uUGFyYW1zEhUKDXZlbG9jaXR5UmF0aW8YASAD",
          "KAISGQoRYWNjZWxlcmF0aW9uUmF0aW8YAiADKAIiOAoOUFRQSm9pbnRQYXJh",
          "bXMSEAoIdmVsb2NpdHkYASADKAISFAoMYWNjZWxlcmF0aW9uGAIgAygCIj0K",
          "E1BUUENvb3JkaW5hdGVQYXJhbXMSEAoIdmVsb2NpdHkYASADKAISFAoMYWNj",
          "ZWxlcmF0aW9uGAIgAygCIkMKD1BUUENvbW1vblBhcmFtcxIVCg12ZWxvY2l0",
          "eVJhdGlvGAEgAygCEhkKEWFjY2VsZXJhdGlvblJhdGlvGAIgAygCIswDCglE",
          "b2JvdERhdGESDAoEbmFtZRgBIAEoCRIKCgJpZBgCIAEoBRIgCglsaXZlU3Rh",
          "dGUYAyABKA4yDS5Db25uZWN0U3RhdGUSEwoEcG9zZRgEIAMoCzIFLlBvc2US",
          "EgoKYWxhcm1TdGF0ZRgFIAEoCRISCgpob21lUGFyYW1zGAYgAygCEhkKEWVu",
          "ZEVmZmVjdG9yUGFyYW1zGAcgAygCEh0KFWVuZEVmZmVjdG9yU3VjdGlvbkN1",
          "cBgIIAMoCBInCg5qb2dKb2ludFBhcmFtcxgJIAMoCzIPLkpvZ0pvaW50UGFy",
          "YW1zEjEKE2pvZ0Nvb3JkaW5hdGVQYXJhbXMYCiADKAsyFC5Kb2dDb29yZGlu",
          "YXRlUGFyYW1zEikKD2pvZ0NvbW1vblBhcmFtcxgLIAMoCzIQLkpPR0NvbW1v",
          "blBhcmFtcxInCg5wdHBKb2ludFBhcmFtcxgMIAMoCzIPLlBUUEpvaW50UGFy",
          "YW1zEjEKE3B0cENvb3JkaW5hdGVQYXJhbXMYDSADKAsyFC5QVFBDb29yZGlu",
          "YXRlUGFyYW1zEikKD3B0cENvbW1vblBhcmFtcxgOIAMoCzIQLlBUUENvbW1v",
          "blBhcmFtcyovCgxDb25uZWN0U3RhdGUSDQoJQ09OTkVDVEVEEAASEAoMRElT",
          "Q09OTkVDVEVEEAFiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ConnectState), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Pose), global::Pose.Parser, new[]{ "EndEffectorCor", "JointAngle" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::JogJointParams), global::JogJointParams.Parser, new[]{ "Velocity", "Acceleration" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::JogCoordinateParams), global::JogCoordinateParams.Parser, new[]{ "Velocity", "Acceleration" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::JOGCommonParams), global::JOGCommonParams.Parser, new[]{ "VelocityRatio", "AccelerationRatio" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PTPJointParams), global::PTPJointParams.Parser, new[]{ "Velocity", "Acceleration" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PTPCoordinateParams), global::PTPCoordinateParams.Parser, new[]{ "Velocity", "Acceleration" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PTPCommonParams), global::PTPCommonParams.Parser, new[]{ "VelocityRatio", "AccelerationRatio" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DobotData), global::DobotData.Parser, new[]{ "Name", "Id", "LiveState", "Pose", "AlarmState", "HomeParams", "EndEffectorParams", "EndEffectorSuctionCup", "JogJointParams", "JogCoordinateParams", "JogCommonParams", "PtpJointParams", "PtpCoordinateParams", "PtpCommonParams" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum ConnectState {
  [pbr::OriginalName("CONNECTED")] Connected = 0,
  [pbr::OriginalName("DISCONNECTED")] Disconnected = 1,
}

#endregion

#region Messages
public sealed partial class Pose : pb::IMessage<Pose>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Pose> _parser = new pb::MessageParser<Pose>(() => new Pose());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Pose> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Pose() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Pose(Pose other) : this() {
    endEffectorCor_ = other.endEffectorCor_.Clone();
    jointAngle_ = other.jointAngle_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Pose Clone() {
    return new Pose(this);
  }

  /// <summary>Field number for the "endEffectorCor" field.</summary>
  public const int EndEffectorCorFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_endEffectorCor_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> endEffectorCor_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> EndEffectorCor {
    get { return endEffectorCor_; }
  }

  /// <summary>Field number for the "jointAngle" field.</summary>
  public const int JointAngleFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_jointAngle_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> jointAngle_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> JointAngle {
    get { return jointAngle_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Pose);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Pose other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!endEffectorCor_.Equals(other.endEffectorCor_)) return false;
    if(!jointAngle_.Equals(other.jointAngle_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= endEffectorCor_.GetHashCode();
    hash ^= jointAngle_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    endEffectorCor_.WriteTo(output, _repeated_endEffectorCor_codec);
    jointAngle_.WriteTo(output, _repeated_jointAngle_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    endEffectorCor_.WriteTo(ref output, _repeated_endEffectorCor_codec);
    jointAngle_.WriteTo(ref output, _repeated_jointAngle_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += endEffectorCor_.CalculateSize(_repeated_endEffectorCor_codec);
    size += jointAngle_.CalculateSize(_repeated_jointAngle_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Pose other) {
    if (other == null) {
      return;
    }
    endEffectorCor_.Add(other.endEffectorCor_);
    jointAngle_.Add(other.jointAngle_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          endEffectorCor_.AddEntriesFrom(input, _repeated_endEffectorCor_codec);
          break;
        }
        case 18:
        case 21: {
          jointAngle_.AddEntriesFrom(input, _repeated_jointAngle_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          endEffectorCor_.AddEntriesFrom(ref input, _repeated_endEffectorCor_codec);
          break;
        }
        case 18:
        case 21: {
          jointAngle_.AddEntriesFrom(ref input, _repeated_jointAngle_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class JogJointParams : pb::IMessage<JogJointParams>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JogJointParams> _parser = new pb::MessageParser<JogJointParams>(() => new JogJointParams());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JogJointParams> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JogJointParams() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JogJointParams(JogJointParams other) : this() {
    velocity_ = other.velocity_.Clone();
    acceleration_ = other.acceleration_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JogJointParams Clone() {
    return new JogJointParams(this);
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_velocity_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> velocity_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Velocity {
    get { return velocity_; }
  }

  /// <summary>Field number for the "acceleration" field.</summary>
  public const int AccelerationFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_acceleration_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> acceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Acceleration {
    get { return acceleration_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JogJointParams);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JogJointParams other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!velocity_.Equals(other.velocity_)) return false;
    if(!acceleration_.Equals(other.acceleration_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= velocity_.GetHashCode();
    hash ^= acceleration_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    velocity_.WriteTo(output, _repeated_velocity_codec);
    acceleration_.WriteTo(output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    velocity_.WriteTo(ref output, _repeated_velocity_codec);
    acceleration_.WriteTo(ref output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += velocity_.CalculateSize(_repeated_velocity_codec);
    size += acceleration_.CalculateSize(_repeated_acceleration_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JogJointParams other) {
    if (other == null) {
      return;
    }
    velocity_.Add(other.velocity_);
    acceleration_.Add(other.acceleration_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(ref input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(ref input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class JogCoordinateParams : pb::IMessage<JogCoordinateParams>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JogCoordinateParams> _parser = new pb::MessageParser<JogCoordinateParams>(() => new JogCoordinateParams());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JogCoordinateParams> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JogCoordinateParams() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JogCoordinateParams(JogCoordinateParams other) : this() {
    velocity_ = other.velocity_.Clone();
    acceleration_ = other.acceleration_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JogCoordinateParams Clone() {
    return new JogCoordinateParams(this);
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_velocity_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> velocity_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Velocity {
    get { return velocity_; }
  }

  /// <summary>Field number for the "acceleration" field.</summary>
  public const int AccelerationFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_acceleration_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> acceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Acceleration {
    get { return acceleration_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JogCoordinateParams);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JogCoordinateParams other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!velocity_.Equals(other.velocity_)) return false;
    if(!acceleration_.Equals(other.acceleration_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= velocity_.GetHashCode();
    hash ^= acceleration_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    velocity_.WriteTo(output, _repeated_velocity_codec);
    acceleration_.WriteTo(output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    velocity_.WriteTo(ref output, _repeated_velocity_codec);
    acceleration_.WriteTo(ref output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += velocity_.CalculateSize(_repeated_velocity_codec);
    size += acceleration_.CalculateSize(_repeated_acceleration_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JogCoordinateParams other) {
    if (other == null) {
      return;
    }
    velocity_.Add(other.velocity_);
    acceleration_.Add(other.acceleration_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(ref input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(ref input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class JOGCommonParams : pb::IMessage<JOGCommonParams>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JOGCommonParams> _parser = new pb::MessageParser<JOGCommonParams>(() => new JOGCommonParams());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JOGCommonParams> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JOGCommonParams() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JOGCommonParams(JOGCommonParams other) : this() {
    velocityRatio_ = other.velocityRatio_.Clone();
    accelerationRatio_ = other.accelerationRatio_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JOGCommonParams Clone() {
    return new JOGCommonParams(this);
  }

  /// <summary>Field number for the "velocityRatio" field.</summary>
  public const int VelocityRatioFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_velocityRatio_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> velocityRatio_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> VelocityRatio {
    get { return velocityRatio_; }
  }

  /// <summary>Field number for the "accelerationRatio" field.</summary>
  public const int AccelerationRatioFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_accelerationRatio_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> accelerationRatio_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> AccelerationRatio {
    get { return accelerationRatio_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JOGCommonParams);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JOGCommonParams other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!velocityRatio_.Equals(other.velocityRatio_)) return false;
    if(!accelerationRatio_.Equals(other.accelerationRatio_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= velocityRatio_.GetHashCode();
    hash ^= accelerationRatio_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    velocityRatio_.WriteTo(output, _repeated_velocityRatio_codec);
    accelerationRatio_.WriteTo(output, _repeated_accelerationRatio_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    velocityRatio_.WriteTo(ref output, _repeated_velocityRatio_codec);
    accelerationRatio_.WriteTo(ref output, _repeated_accelerationRatio_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += velocityRatio_.CalculateSize(_repeated_velocityRatio_codec);
    size += accelerationRatio_.CalculateSize(_repeated_accelerationRatio_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JOGCommonParams other) {
    if (other == null) {
      return;
    }
    velocityRatio_.Add(other.velocityRatio_);
    accelerationRatio_.Add(other.accelerationRatio_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          velocityRatio_.AddEntriesFrom(input, _repeated_velocityRatio_codec);
          break;
        }
        case 18:
        case 21: {
          accelerationRatio_.AddEntriesFrom(input, _repeated_accelerationRatio_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          velocityRatio_.AddEntriesFrom(ref input, _repeated_velocityRatio_codec);
          break;
        }
        case 18:
        case 21: {
          accelerationRatio_.AddEntriesFrom(ref input, _repeated_accelerationRatio_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PTPJointParams : pb::IMessage<PTPJointParams>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PTPJointParams> _parser = new pb::MessageParser<PTPJointParams>(() => new PTPJointParams());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PTPJointParams> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPJointParams() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPJointParams(PTPJointParams other) : this() {
    velocity_ = other.velocity_.Clone();
    acceleration_ = other.acceleration_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPJointParams Clone() {
    return new PTPJointParams(this);
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_velocity_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> velocity_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Velocity {
    get { return velocity_; }
  }

  /// <summary>Field number for the "acceleration" field.</summary>
  public const int AccelerationFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_acceleration_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> acceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Acceleration {
    get { return acceleration_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PTPJointParams);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PTPJointParams other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!velocity_.Equals(other.velocity_)) return false;
    if(!acceleration_.Equals(other.acceleration_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= velocity_.GetHashCode();
    hash ^= acceleration_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    velocity_.WriteTo(output, _repeated_velocity_codec);
    acceleration_.WriteTo(output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    velocity_.WriteTo(ref output, _repeated_velocity_codec);
    acceleration_.WriteTo(ref output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += velocity_.CalculateSize(_repeated_velocity_codec);
    size += acceleration_.CalculateSize(_repeated_acceleration_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PTPJointParams other) {
    if (other == null) {
      return;
    }
    velocity_.Add(other.velocity_);
    acceleration_.Add(other.acceleration_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(ref input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(ref input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PTPCoordinateParams : pb::IMessage<PTPCoordinateParams>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PTPCoordinateParams> _parser = new pb::MessageParser<PTPCoordinateParams>(() => new PTPCoordinateParams());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PTPCoordinateParams> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPCoordinateParams() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPCoordinateParams(PTPCoordinateParams other) : this() {
    velocity_ = other.velocity_.Clone();
    acceleration_ = other.acceleration_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPCoordinateParams Clone() {
    return new PTPCoordinateParams(this);
  }

  /// <summary>Field number for the "velocity" field.</summary>
  public const int VelocityFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_velocity_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> velocity_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Velocity {
    get { return velocity_; }
  }

  /// <summary>Field number for the "acceleration" field.</summary>
  public const int AccelerationFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_acceleration_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> acceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> Acceleration {
    get { return acceleration_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PTPCoordinateParams);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PTPCoordinateParams other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!velocity_.Equals(other.velocity_)) return false;
    if(!acceleration_.Equals(other.acceleration_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= velocity_.GetHashCode();
    hash ^= acceleration_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    velocity_.WriteTo(output, _repeated_velocity_codec);
    acceleration_.WriteTo(output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    velocity_.WriteTo(ref output, _repeated_velocity_codec);
    acceleration_.WriteTo(ref output, _repeated_acceleration_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += velocity_.CalculateSize(_repeated_velocity_codec);
    size += acceleration_.CalculateSize(_repeated_acceleration_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PTPCoordinateParams other) {
    if (other == null) {
      return;
    }
    velocity_.Add(other.velocity_);
    acceleration_.Add(other.acceleration_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          velocity_.AddEntriesFrom(ref input, _repeated_velocity_codec);
          break;
        }
        case 18:
        case 21: {
          acceleration_.AddEntriesFrom(ref input, _repeated_acceleration_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PTPCommonParams : pb::IMessage<PTPCommonParams>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PTPCommonParams> _parser = new pb::MessageParser<PTPCommonParams>(() => new PTPCommonParams());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PTPCommonParams> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPCommonParams() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPCommonParams(PTPCommonParams other) : this() {
    velocityRatio_ = other.velocityRatio_.Clone();
    accelerationRatio_ = other.accelerationRatio_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTPCommonParams Clone() {
    return new PTPCommonParams(this);
  }

  /// <summary>Field number for the "velocityRatio" field.</summary>
  public const int VelocityRatioFieldNumber = 1;
  private static readonly pb::FieldCodec<float> _repeated_velocityRatio_codec
      = pb::FieldCodec.ForFloat(10);
  private readonly pbc::RepeatedField<float> velocityRatio_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> VelocityRatio {
    get { return velocityRatio_; }
  }

  /// <summary>Field number for the "accelerationRatio" field.</summary>
  public const int AccelerationRatioFieldNumber = 2;
  private static readonly pb::FieldCodec<float> _repeated_accelerationRatio_codec
      = pb::FieldCodec.ForFloat(18);
  private readonly pbc::RepeatedField<float> accelerationRatio_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> AccelerationRatio {
    get { return accelerationRatio_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PTPCommonParams);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PTPCommonParams other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!velocityRatio_.Equals(other.velocityRatio_)) return false;
    if(!accelerationRatio_.Equals(other.accelerationRatio_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= velocityRatio_.GetHashCode();
    hash ^= accelerationRatio_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    velocityRatio_.WriteTo(output, _repeated_velocityRatio_codec);
    accelerationRatio_.WriteTo(output, _repeated_accelerationRatio_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    velocityRatio_.WriteTo(ref output, _repeated_velocityRatio_codec);
    accelerationRatio_.WriteTo(ref output, _repeated_accelerationRatio_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += velocityRatio_.CalculateSize(_repeated_velocityRatio_codec);
    size += accelerationRatio_.CalculateSize(_repeated_accelerationRatio_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PTPCommonParams other) {
    if (other == null) {
      return;
    }
    velocityRatio_.Add(other.velocityRatio_);
    accelerationRatio_.Add(other.accelerationRatio_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 13: {
          velocityRatio_.AddEntriesFrom(input, _repeated_velocityRatio_codec);
          break;
        }
        case 18:
        case 21: {
          accelerationRatio_.AddEntriesFrom(input, _repeated_accelerationRatio_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 13: {
          velocityRatio_.AddEntriesFrom(ref input, _repeated_velocityRatio_codec);
          break;
        }
        case 18:
        case 21: {
          accelerationRatio_.AddEntriesFrom(ref input, _repeated_accelerationRatio_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DobotData : pb::IMessage<DobotData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DobotData> _parser = new pb::MessageParser<DobotData>(() => new DobotData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DobotData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DataReflection.Descriptor.MessageTypes[7]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DobotData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DobotData(DobotData other) : this() {
    name_ = other.name_;
    id_ = other.id_;
    liveState_ = other.liveState_;
    pose_ = other.pose_.Clone();
    alarmState_ = other.alarmState_;
    homeParams_ = other.homeParams_.Clone();
    endEffectorParams_ = other.endEffectorParams_.Clone();
    endEffectorSuctionCup_ = other.endEffectorSuctionCup_.Clone();
    jogJointParams_ = other.jogJointParams_.Clone();
    jogCoordinateParams_ = other.jogCoordinateParams_.Clone();
    jogCommonParams_ = other.jogCommonParams_.Clone();
    ptpJointParams_ = other.ptpJointParams_.Clone();
    ptpCoordinateParams_ = other.ptpCoordinateParams_.Clone();
    ptpCommonParams_ = other.ptpCommonParams_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DobotData Clone() {
    return new DobotData(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 2;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "liveState" field.</summary>
  public const int LiveStateFieldNumber = 3;
  private global::ConnectState liveState_ = global::ConnectState.Connected;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ConnectState LiveState {
    get { return liveState_; }
    set {
      liveState_ = value;
    }
  }

  /// <summary>Field number for the "pose" field.</summary>
  public const int PoseFieldNumber = 4;
  private static readonly pb::FieldCodec<global::Pose> _repeated_pose_codec
      = pb::FieldCodec.ForMessage(34, global::Pose.Parser);
  private readonly pbc::RepeatedField<global::Pose> pose_ = new pbc::RepeatedField<global::Pose>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Pose> Pose {
    get { return pose_; }
  }

  /// <summary>Field number for the "alarmState" field.</summary>
  public const int AlarmStateFieldNumber = 5;
  private string alarmState_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AlarmState {
    get { return alarmState_; }
    set {
      alarmState_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "homeParams" field.</summary>
  public const int HomeParamsFieldNumber = 6;
  private static readonly pb::FieldCodec<float> _repeated_homeParams_codec
      = pb::FieldCodec.ForFloat(50);
  private readonly pbc::RepeatedField<float> homeParams_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> HomeParams {
    get { return homeParams_; }
  }

  /// <summary>Field number for the "endEffectorParams" field.</summary>
  public const int EndEffectorParamsFieldNumber = 7;
  private static readonly pb::FieldCodec<float> _repeated_endEffectorParams_codec
      = pb::FieldCodec.ForFloat(58);
  private readonly pbc::RepeatedField<float> endEffectorParams_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> EndEffectorParams {
    get { return endEffectorParams_; }
  }

  /// <summary>Field number for the "endEffectorSuctionCup" field.</summary>
  public const int EndEffectorSuctionCupFieldNumber = 8;
  private static readonly pb::FieldCodec<bool> _repeated_endEffectorSuctionCup_codec
      = pb::FieldCodec.ForBool(66);
  private readonly pbc::RepeatedField<bool> endEffectorSuctionCup_ = new pbc::RepeatedField<bool>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<bool> EndEffectorSuctionCup {
    get { return endEffectorSuctionCup_; }
  }

  /// <summary>Field number for the "jogJointParams" field.</summary>
  public const int JogJointParamsFieldNumber = 9;
  private static readonly pb::FieldCodec<global::JogJointParams> _repeated_jogJointParams_codec
      = pb::FieldCodec.ForMessage(74, global::JogJointParams.Parser);
  private readonly pbc::RepeatedField<global::JogJointParams> jogJointParams_ = new pbc::RepeatedField<global::JogJointParams>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::JogJointParams> JogJointParams {
    get { return jogJointParams_; }
  }

  /// <summary>Field number for the "jogCoordinateParams" field.</summary>
  public const int JogCoordinateParamsFieldNumber = 10;
  private static readonly pb::FieldCodec<global::JogCoordinateParams> _repeated_jogCoordinateParams_codec
      = pb::FieldCodec.ForMessage(82, global::JogCoordinateParams.Parser);
  private readonly pbc::RepeatedField<global::JogCoordinateParams> jogCoordinateParams_ = new pbc::RepeatedField<global::JogCoordinateParams>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::JogCoordinateParams> JogCoordinateParams {
    get { return jogCoordinateParams_; }
  }

  /// <summary>Field number for the "jogCommonParams" field.</summary>
  public const int JogCommonParamsFieldNumber = 11;
  private static readonly pb::FieldCodec<global::JOGCommonParams> _repeated_jogCommonParams_codec
      = pb::FieldCodec.ForMessage(90, global::JOGCommonParams.Parser);
  private readonly pbc::RepeatedField<global::JOGCommonParams> jogCommonParams_ = new pbc::RepeatedField<global::JOGCommonParams>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::JOGCommonParams> JogCommonParams {
    get { return jogCommonParams_; }
  }

  /// <summary>Field number for the "ptpJointParams" field.</summary>
  public const int PtpJointParamsFieldNumber = 12;
  private static readonly pb::FieldCodec<global::PTPJointParams> _repeated_ptpJointParams_codec
      = pb::FieldCodec.ForMessage(98, global::PTPJointParams.Parser);
  private readonly pbc::RepeatedField<global::PTPJointParams> ptpJointParams_ = new pbc::RepeatedField<global::PTPJointParams>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PTPJointParams> PtpJointParams {
    get { return ptpJointParams_; }
  }

  /// <summary>Field number for the "ptpCoordinateParams" field.</summary>
  public const int PtpCoordinateParamsFieldNumber = 13;
  private static readonly pb::FieldCodec<global::PTPCoordinateParams> _repeated_ptpCoordinateParams_codec
      = pb::FieldCodec.ForMessage(106, global::PTPCoordinateParams.Parser);
  private readonly pbc::RepeatedField<global::PTPCoordinateParams> ptpCoordinateParams_ = new pbc::RepeatedField<global::PTPCoordinateParams>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PTPCoordinateParams> PtpCoordinateParams {
    get { return ptpCoordinateParams_; }
  }

  /// <summary>Field number for the "ptpCommonParams" field.</summary>
  public const int PtpCommonParamsFieldNumber = 14;
  private static readonly pb::FieldCodec<global::PTPCommonParams> _repeated_ptpCommonParams_codec
      = pb::FieldCodec.ForMessage(114, global::PTPCommonParams.Parser);
  private readonly pbc::RepeatedField<global::PTPCommonParams> ptpCommonParams_ = new pbc::RepeatedField<global::PTPCommonParams>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::PTPCommonParams> PtpCommonParams {
    get { return ptpCommonParams_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DobotData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DobotData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Id != other.Id) return false;
    if (LiveState != other.LiveState) return false;
    if(!pose_.Equals(other.pose_)) return false;
    if (AlarmState != other.AlarmState) return false;
    if(!homeParams_.Equals(other.homeParams_)) return false;
    if(!endEffectorParams_.Equals(other.endEffectorParams_)) return false;
    if(!endEffectorSuctionCup_.Equals(other.endEffectorSuctionCup_)) return false;
    if(!jogJointParams_.Equals(other.jogJointParams_)) return false;
    if(!jogCoordinateParams_.Equals(other.jogCoordinateParams_)) return false;
    if(!jogCommonParams_.Equals(other.jogCommonParams_)) return false;
    if(!ptpJointParams_.Equals(other.ptpJointParams_)) return false;
    if(!ptpCoordinateParams_.Equals(other.ptpCoordinateParams_)) return false;
    if(!ptpCommonParams_.Equals(other.ptpCommonParams_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Id != 0) hash ^= Id.GetHashCode();
    if (LiveState != global::ConnectState.Connected) hash ^= LiveState.GetHashCode();
    hash ^= pose_.GetHashCode();
    if (AlarmState.Length != 0) hash ^= AlarmState.GetHashCode();
    hash ^= homeParams_.GetHashCode();
    hash ^= endEffectorParams_.GetHashCode();
    hash ^= endEffectorSuctionCup_.GetHashCode();
    hash ^= jogJointParams_.GetHashCode();
    hash ^= jogCoordinateParams_.GetHashCode();
    hash ^= jogCommonParams_.GetHashCode();
    hash ^= ptpJointParams_.GetHashCode();
    hash ^= ptpCoordinateParams_.GetHashCode();
    hash ^= ptpCommonParams_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Id != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Id);
    }
    if (LiveState != global::ConnectState.Connected) {
      output.WriteRawTag(24);
      output.WriteEnum((int) LiveState);
    }
    pose_.WriteTo(output, _repeated_pose_codec);
    if (AlarmState.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AlarmState);
    }
    homeParams_.WriteTo(output, _repeated_homeParams_codec);
    endEffectorParams_.WriteTo(output, _repeated_endEffectorParams_codec);
    endEffectorSuctionCup_.WriteTo(output, _repeated_endEffectorSuctionCup_codec);
    jogJointParams_.WriteTo(output, _repeated_jogJointParams_codec);
    jogCoordinateParams_.WriteTo(output, _repeated_jogCoordinateParams_codec);
    jogCommonParams_.WriteTo(output, _repeated_jogCommonParams_codec);
    ptpJointParams_.WriteTo(output, _repeated_ptpJointParams_codec);
    ptpCoordinateParams_.WriteTo(output, _repeated_ptpCoordinateParams_codec);
    ptpCommonParams_.WriteTo(output, _repeated_ptpCommonParams_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Id != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Id);
    }
    if (LiveState != global::ConnectState.Connected) {
      output.WriteRawTag(24);
      output.WriteEnum((int) LiveState);
    }
    pose_.WriteTo(ref output, _repeated_pose_codec);
    if (AlarmState.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(AlarmState);
    }
    homeParams_.WriteTo(ref output, _repeated_homeParams_codec);
    endEffectorParams_.WriteTo(ref output, _repeated_endEffectorParams_codec);
    endEffectorSuctionCup_.WriteTo(ref output, _repeated_endEffectorSuctionCup_codec);
    jogJointParams_.WriteTo(ref output, _repeated_jogJointParams_codec);
    jogCoordinateParams_.WriteTo(ref output, _repeated_jogCoordinateParams_codec);
    jogCommonParams_.WriteTo(ref output, _repeated_jogCommonParams_codec);
    ptpJointParams_.WriteTo(ref output, _repeated_ptpJointParams_codec);
    ptpCoordinateParams_.WriteTo(ref output, _repeated_ptpCoordinateParams_codec);
    ptpCommonParams_.WriteTo(ref output, _repeated_ptpCommonParams_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (LiveState != global::ConnectState.Connected) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LiveState);
    }
    size += pose_.CalculateSize(_repeated_pose_codec);
    if (AlarmState.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AlarmState);
    }
    size += homeParams_.CalculateSize(_repeated_homeParams_codec);
    size += endEffectorParams_.CalculateSize(_repeated_endEffectorParams_codec);
    size += endEffectorSuctionCup_.CalculateSize(_repeated_endEffectorSuctionCup_codec);
    size += jogJointParams_.CalculateSize(_repeated_jogJointParams_codec);
    size += jogCoordinateParams_.CalculateSize(_repeated_jogCoordinateParams_codec);
    size += jogCommonParams_.CalculateSize(_repeated_jogCommonParams_codec);
    size += ptpJointParams_.CalculateSize(_repeated_ptpJointParams_codec);
    size += ptpCoordinateParams_.CalculateSize(_repeated_ptpCoordinateParams_codec);
    size += ptpCommonParams_.CalculateSize(_repeated_ptpCommonParams_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DobotData other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.LiveState != global::ConnectState.Connected) {
      LiveState = other.LiveState;
    }
    pose_.Add(other.pose_);
    if (other.AlarmState.Length != 0) {
      AlarmState = other.AlarmState;
    }
    homeParams_.Add(other.homeParams_);
    endEffectorParams_.Add(other.endEffectorParams_);
    endEffectorSuctionCup_.Add(other.endEffectorSuctionCup_);
    jogJointParams_.Add(other.jogJointParams_);
    jogCoordinateParams_.Add(other.jogCoordinateParams_);
    jogCommonParams_.Add(other.jogCommonParams_);
    ptpJointParams_.Add(other.ptpJointParams_);
    ptpCoordinateParams_.Add(other.ptpCoordinateParams_);
    ptpCommonParams_.Add(other.ptpCommonParams_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Id = input.ReadInt32();
          break;
        }
        case 24: {
          LiveState = (global::ConnectState) input.ReadEnum();
          break;
        }
        case 34: {
          pose_.AddEntriesFrom(input, _repeated_pose_codec);
          break;
        }
        case 42: {
          AlarmState = input.ReadString();
          break;
        }
        case 50:
        case 53: {
          homeParams_.AddEntriesFrom(input, _repeated_homeParams_codec);
          break;
        }
        case 58:
        case 61: {
          endEffectorParams_.AddEntriesFrom(input, _repeated_endEffectorParams_codec);
          break;
        }
        case 66:
        case 64: {
          endEffectorSuctionCup_.AddEntriesFrom(input, _repeated_endEffectorSuctionCup_codec);
          break;
        }
        case 74: {
          jogJointParams_.AddEntriesFrom(input, _repeated_jogJointParams_codec);
          break;
        }
        case 82: {
          jogCoordinateParams_.AddEntriesFrom(input, _repeated_jogCoordinateParams_codec);
          break;
        }
        case 90: {
          jogCommonParams_.AddEntriesFrom(input, _repeated_jogCommonParams_codec);
          break;
        }
        case 98: {
          ptpJointParams_.AddEntriesFrom(input, _repeated_ptpJointParams_codec);
          break;
        }
        case 106: {
          ptpCoordinateParams_.AddEntriesFrom(input, _repeated_ptpCoordinateParams_codec);
          break;
        }
        case 114: {
          ptpCommonParams_.AddEntriesFrom(input, _repeated_ptpCommonParams_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Id = input.ReadInt32();
          break;
        }
        case 24: {
          LiveState = (global::ConnectState) input.ReadEnum();
          break;
        }
        case 34: {
          pose_.AddEntriesFrom(ref input, _repeated_pose_codec);
          break;
        }
        case 42: {
          AlarmState = input.ReadString();
          break;
        }
        case 50:
        case 53: {
          homeParams_.AddEntriesFrom(ref input, _repeated_homeParams_codec);
          break;
        }
        case 58:
        case 61: {
          endEffectorParams_.AddEntriesFrom(ref input, _repeated_endEffectorParams_codec);
          break;
        }
        case 66:
        case 64: {
          endEffectorSuctionCup_.AddEntriesFrom(ref input, _repeated_endEffectorSuctionCup_codec);
          break;
        }
        case 74: {
          jogJointParams_.AddEntriesFrom(ref input, _repeated_jogJointParams_codec);
          break;
        }
        case 82: {
          jogCoordinateParams_.AddEntriesFrom(ref input, _repeated_jogCoordinateParams_codec);
          break;
        }
        case 90: {
          jogCommonParams_.AddEntriesFrom(ref input, _repeated_jogCommonParams_codec);
          break;
        }
        case 98: {
          ptpJointParams_.AddEntriesFrom(ref input, _repeated_ptpJointParams_codec);
          break;
        }
        case 106: {
          ptpCoordinateParams_.AddEntriesFrom(ref input, _repeated_ptpCoordinateParams_codec);
          break;
        }
        case 114: {
          ptpCommonParams_.AddEntriesFrom(ref input, _repeated_ptpCommonParams_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
